version: '3.8'

services:
  # Lite Speed
  php8-litespeed:
    container_name: php8-litespeed
    build:
      context: .
      args:
        - LSPHP_VERSION=${LSPHP_VERSION}
    ports:
      - "7080:7080"
      - "8088:8088"
    volumes:
      - ./www:/var/www
      - ./docker/httpd/config/httpd_config.conf:/usr/local/lsws/conf/httpd_config.conf
      - ./docker/httpd/config/vhconf.conf:/usr/local/lsws/conf/vhosts/www/vhconf.conf
  # MySQL
  db:
    image: mysql:5.7
    container_name: litespeed_mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payment_master
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    container_name: dev_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=litespeed_mysql_host
    - PMA_USER=root
    - PMA_PASSWORD=password
    ports:
    - 8080:80